
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int Nombre = 37;
  public static final int Parentesis_Cierre = 26;
  public static final int Inicio_Fila = 10;
  public static final int Inicio_Tabla = 8;
  public static final int Inicio_Imagen = 18;
  public static final int Fin_Doc_html = 3;
  public static final int Signo_multiplicacion = 28;
  public static final int Fin_Cuerpo = 7;
  public static final int Enlace = 21;
  public static final int Separador = 32;
  public static final int Titulo = 15;
  public static final int Parentesis_Aper = 25;
  public static final int Columna = 13;
  public static final int Inicio_Doc_html = 2;
  public static final int Fin_Lista = 12;
  public static final int EOF = 0;
  public static final int Signo_Suma = 29;
  public static final int error = 1;
  public static final int Numeros = 34;
  public static final int Fin_Tabla = 9;
  public static final int Fin_Encabezado = 5;
  public static final int Inicio_Cuerpo = 6;
  public static final int Imprimir = 23;
  public static final int Borde = 14;
  public static final int Correo = 35;
  public static final int Inicio_Encabezado = 4;
  public static final int Dos_puntos = 33;
  public static final int Fin_Imagen = 19;
  public static final int Ancho = 36;
  public static final int Identificador = 20;
  public static final int Altura = 38;
  public static final int Fin_Fila = 17;
  public static final int Punto_coma = 31;
  public static final int Decimal = 39;
  public static final int Negrita = 16;
  public static final int Signo_resta = 30;
  public static final int EnlaceR = 22;
  public static final int Igual = 27;
  public static final int Inicio_Lista = 11;
  public static final int Comillas = 24;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Inicio_Doc_html",
  "Fin_Doc_html",
  "Inicio_Encabezado",
  "Fin_Encabezado",
  "Inicio_Cuerpo",
  "Fin_Cuerpo",
  "Inicio_Tabla",
  "Fin_Tabla",
  "Inicio_Fila",
  "Inicio_Lista",
  "Fin_Lista",
  "Columna",
  "Borde",
  "Titulo",
  "Negrita",
  "Fin_Fila",
  "Inicio_Imagen",
  "Fin_Imagen",
  "Identificador",
  "Enlace",
  "EnlaceR",
  "Imprimir",
  "Comillas",
  "Parentesis_Aper",
  "Parentesis_Cierre",
  "Igual",
  "Signo_multiplicacion",
  "Signo_Suma",
  "Signo_resta",
  "Punto_coma",
  "Separador",
  "Dos_puntos",
  "Numeros",
  "Correo",
  "Ancho",
  "Nombre",
  "Altura",
  "Decimal"
  };
}

